import { PerformanceAlbum, VideoItem, SpotlightItem, TestimonialSnapshot } from "./types"

export const performanceAlbumsData: PerformanceAlbum[] = [
  {
    id: "1",
    title: "Annual Day 2024 - Cultural Extravaganza",
    slug: "annual-day-2024",
    description: "A spectacular showcase featuring over 200 students performing across 15 dance forms, celebrating culture and creativity.",
    date: "2024-12-15",
    category: "annual-day",
    coverImage: "/assets/1.jpg",
    imageCount: 45,
    location: "St. Joseph's School Auditorium, Trichy",
    images: [
      {
        id: "1-1",
        url: "/assets/1.jpg",
        title: "Opening Act - Classical Fusion",
        albumId: "1",
        category: "annual-day",
        style: "classical",
        capturedDate: "2024-12-15",
        tags: ["bharatanatyam", "group-performance"],
      },
      {
        id: "1-2",
        url: "/assets/2.jpg",
        title: "Kids Performance - Fairy Tale Theme",
        albumId: "1",
        category: "annual-day",
        style: "kids",
        capturedDate: "2024-12-15",
      },
    ],
  },
  {
    id: "2",
    title: "ESP Showcase 2024 - Student Excellence",
    slug: "esp-showcase-2024",
    description: "Empowering Student Performance program highlighting young talent through professionally choreographed productions.",
    date: "2024-11-20",
    category: "esp-showcase",
    coverImage: "/assets/3.jpg",
    imageCount: 38,
    location: "National School, Trichy",
    images: [
      {
        id: "2-1",
        url: "/assets/3.jpg",
        title: "Contemporary Group Performance",
        albumId: "2",
        category: "esp-showcase",
        style: "western",
        capturedDate: "2024-11-20",
      },
    ],
  },
  {
    id: "3",
    title: "Corporate Gala Night - TCS Trichy",
    slug: "corporate-gala-tcs",
    description: "Professional entertainment for TCS annual celebration featuring Bollywood and contemporary performances.",
    date: "2024-10-05",
    category: "corporate",
    coverImage: "/assets/5.jpg",
    imageCount: 28,
    location: "Grand Plaza Hotel, Trichy",
    images: [
      {
        id: "3-1",
        url: "/assets/5.jpg",
        title: "Bollywood Medley Performance",
        albumId: "3",
        category: "corporate",
        style: "bollywood",
        capturedDate: "2024-10-05",
      },
    ],
  },
  {
    id: "4",
    title: "Fusion Fashion Show 2024",
    slug: "fusion-fashion-2024",
    description: "Runway meets dance in this unique fashion showcase blending traditional and contemporary aesthetics.",
    date: "2024-09-12",
    category: "fashion",
    coverImage: "/assets/7.jpg",
    imageCount: 32,
    location: "Fashion District, Trichy",
    images: [
      {
        id: "4-1",
        url: "/assets/7.jpg",
        title: "La Ramp Collection Launch",
        albumId: "4",
        category: "fashion",
        capturedDate: "2024-09-12",
      },
    ],
  },
  {
    id: "5",
    title: "Summer Dance Workshop 2024",
    slug: "summer-workshop-2024",
    description: "Intensive 6-week program with over 100 participants learning multiple dance forms and choreography basics.",
    date: "2024-05-30",
    category: "workshops",
    coverImage: "/assets/9.jpg",
    imageCount: 52,
    location: "Edwin's Dance Studio, Trichy",
    images: [
      {
        id: "5-1",
        url: "/assets/9.jpg",
        title: "Workshop Finale Performance",
        albumId: "5",
        category: "workshops",
        capturedDate: "2024-05-30",
      },
    ],
  },
  {
    id: "6",
    title: "LED Spectacular - Innovation in Dance",
    slug: "led-spectacular-2024",
    description: "Cutting-edge performance combining LED technology with synchronized choreography for a visual masterpiece.",
    date: "2024-08-18",
    category: "theme-shows",
    coverImage: "/assets/11.jpg",
    imageCount: 25,
    location: "Trichy Convention Center",
    images: [
      {
        id: "6-1",
        url: "/assets/11.jpg",
        title: "LED Group Synchronization",
        albumId: "6",
        category: "theme-shows",
        style: "led",
        capturedDate: "2024-08-18",
      },
    ],
  },
]

export const costumeBackstageImages = [
  {
    id: "c-1",
    url: "/assets/1.jpg",
    title: "Bharatanatyam Costume Detail",
    description: "Handcrafted silk costume with intricate zari embroidery",
    albumId: "backstage",
    category: "annual-day" as const,
    capturedDate: "2024-12-10",
    isCostume: true,
  },
  {
    id: "c-2",
    url: "/assets/2.jpg",
    title: "Backstage Preparation",
    description: "Team getting ready 30 minutes before showtime",
    albumId: "backstage",
    category: "theme-shows" as const,
    capturedDate: "2024-11-15",
    isBackstage: true,
  },
  {
    id: "c-3",
    url: "/assets/3.jpg",
    title: "Props & Accessories",
    description: "Collection of traditional and modern dance props",
    albumId: "backstage",
    category: "workshops" as const,
    capturedDate: "2024-10-20",
    isCostume: true,
  },
  {
    id: "c-4",
    url: "/assets/4.jpg",
    title: "Makeup Artistry",
    description: "Professional stage makeup transformation",
    albumId: "backstage",
    category: "corporate" as const,
    capturedDate: "2024-09-25",
    isBackstage: true,
  },
]

export const videosData: VideoItem[] = [
  {
    id: "v-1",
    title: "Annual Day 2024 Highlights",
    description: "5-minute recap of our biggest annual production featuring 200+ performers",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnailUrl: "/assets/1.jpg",
    source: "youtube",
    category: "annual-day",
    duration: "5:23",
    uploadDate: "2024-12-20",
  },
  {
    id: "v-2",
    title: "Chair Co-cise Session Reel",
    description: "Innovative low-impact dance fitness program for all ages",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnailUrl: "/assets/13.jpg",
    source: "youtube",
    category: "workshops",
    duration: "2:45",
    uploadDate: "2024-11-10",
  },
  {
    id: "v-3",
    title: "Corporate Event Performance",
    description: "Professional entertainment for TCS annual gala",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnailUrl: "/assets/5.jpg",
    source: "youtube",
    category: "corporate",
    duration: "4:12",
    uploadDate: "2024-10-08",
  },
  {
    id: "v-4",
    title: "Fashion Show Runway Dance",
    description: "La Ramp collection launch with choreographed runway walk",
    url: "https://www.youtube.com/embed/dQw4w9WgXcQ",
    thumbnailUrl: "/assets/7.jpg",
    source: "youtube",
    category: "fashion",
    duration: "3:50",
    uploadDate: "2024-09-15",
  },
]

export const spotlightData: SpotlightItem[] = [
  {
    id: "s-1",
    name: "Priya Nair",
    title: "Outstanding Student Performer",
    description: "Won Best Dancer award at State-level competition",
    image: "/assets/2.jpg",
    achievement: "State Level Dance Championship - Gold Medal",
    year: 2024,
    category: "student",
  },
  {
    id: "s-2",
    name: "Rajesh Kumar",
    title: "Alumni Success Story",
    description: "Now a professional choreographer working in Kollywood",
    image: "/assets/4.jpg",
    achievement: "Choreographer for 5 Tamil Films",
    year: 2024,
    category: "alumni",
  },
  {
    id: "s-3",
    name: "Ananya Sharma",
    title: "Junior Champion",
    description: "Youngest student to perform solo at annual day",
    image: "/assets/6.jpg",
    achievement: "Solo Performance at Age 8",
    year: 2024,
    category: "student",
  },
  {
    id: "s-4",
    name: "Vikram Reddy",
    title: "International Performer",
    description: "Represented India at cultural exchange program in Singapore",
    image: "/assets/8.jpg",
    achievement: "Cultural Ambassador - Singapore",
    year: 2024,
    category: "alumni",
  },
]

export const testimonialSnapshotsData: TestimonialSnapshot[] = [
  {
    id: "t-1",
    image: "/assets/1.jpg",
    quote: "Edwin's transformed my daughter's confidence. She's now a star performer!",
    author: "Mrs. Lakshmi Menon",
    role: "Parent",
    event: "Annual Day 2024",
  },
  {
    id: "t-2",
    image: "/assets/3.jpg",
    quote: "The professionalism and creativity exceeded all our expectations.",
    author: "Mr. Arun Kumar",
    role: "Corporate Client - TCS",
    event: "Corporate Gala 2024",
  },
  {
    id: "t-3",
    image: "/assets/5.jpg",
    quote: "Best dance training in Trichy. The instructors are world-class!",
    author: "Priya Sharma",
    role: "Student",
    event: "Summer Workshop 2024",
  },
  {
    id: "t-4",
    image: "/assets/7.jpg",
    quote: "Our fashion show was elevated by Edwin's choreography expertise.",
    author: "Designer Sanjana",
    role: "Fashion Designer",
    event: "Fashion Show 2024",
  },
]

export const categoryLabels = {
  "all": "All Galleries",
  "annual-day": "Annual Day",
  "theme-shows": "Theme Shows",
  "esp-showcase": "ESP Showcase",
  "corporate": "Corporate Events",
  "fashion": "Fashion Shows",
  "workshops": "Workshops",
}

export const styleLabels = {
  "western": "Western",
  "bollywood": "Bollywood",
  "chair-co-cise": "Chair Co-cise",
  "kids": "Kids Performances",
  "led": "LED Shows",
  "classical": "Classical",
}
